# ----------------------------------------------------------------------------------
# Commands to run this compose file:
#
#   docker compose -p classmate_app-integrated -f docker-compose.yml up -d
#       - Starts containers in detached mode (-d)
#       - Uses existing images if already built
#
#   docker compose -p classmate_app-integrated -f docker-compose.yml up -d --build
#       - Forces rebuild of images before starting containers
# ----------------------------------------------------------------------------------

# version: '3.9'

services:

  # ===============================
  # PostgreSQL
  # ===============================
  postgres:
    image: postgres:15
    container_name: classmate-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - classmate-network

  # ===============================
  # MongoDB
  # ===============================
  mongodb:
    image: mongo:7
    container_name: classmate-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - classmate-network

  # ===============================
  # User Service
  # ===============================
  user-service:
    build:
      context: ./user-service
    image: classmate_app-integrated-user-service
    container_name: user-service
    depends_on:
        - postgres
    environment:
        SPRING_PROFILES_ACTIVE: docker
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classmate
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
    ports:
        - "8088:8089"
    restart: unless-stopped
    networks:
        - classmate-network

  # ===============================
  # Course Service
  # ===============================
  course-service:
    build:
      context: ./course-service
    image: classmate_app-integrated-course-service
    container_name: course-service
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classmate
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8084:8080"
    networks:
      - classmate-network

  # ===============================
  # Grade Service
  # ===============================
  grade-service:
    build:
      context: ./grade-service
    image: classmate_app-integrated-grade-service
    container_name: grade-service
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classmate
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8085:8081"
    networks:
      - classmate-network

  # ===============================
  # Task Service
  # ===============================
  task-service:
    build:
      context: ./task-service
    image: classmate_app-integrated-task-service
    container_name: task-service
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8086:8083"
    restart: unless-stopped
    networks:
      - classmate-network

  # ===============================
  # Reminder Service
  # ===============================
  reminder-service:
    build:
      context: ./reminder-service
    image: classmate_app-integrated-reminder-service
    container_name: reminder-service
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8087:8082"
    restart: unless-stopped
    networks:
      - classmate-network

  # ===============================
  # API Gateway
  # ===============================
  api-gateway:
    build:
      context: ./api-gateway
    image: classmate_app-integrated-api-gateway
    container_name: api-gateway
    depends_on:
      - user-service
      - course-service
      - grade-service
      - task-service
      - reminder-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8091:8080"
    restart: unless-stopped
    networks:
      - classmate-network

  # ===============================
  # Keycloak
  # ===============================
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    networks:
      - classmate-network

networks:
  classmate-network:
    driver: bridge
